workspace:
  base: /go/src
  path: github.com/makii42/swaggerui

pipeline:
  gen:
    image: makii42/bindata-builder
    commands:
      - make gen
  untouched:
    image: makii42/untouched:v0.0.2
    commands:
    - untouched