version: 2
jobs:
  generate:
    docker: 
      - image: makii42/bindata-builder:latest
    working_directory: /go/src/github.com/makii42/swaggerui
    steps:
      - checkout
      - run: go-bindata -pkg swaggerui -o ./bindata.go ./assets
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  verify:
    docker:
      - image: makii42/untouched:latest
    working_directory: /go/src/github.com/makii42/swaggerui
    steps: 
      - attach_workspace:
          at: .
      - run: untouched

  test:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: /go/src/github.com/makii42/swaggerui
    steps:
      - run: go build .
      - persist_to_workspace:
          root: .
          paths:
            - "*"


workflows:
  version: 2
  all:
    jobs: 
      - generate
      - verify:
          requires: 
            - generate
      - test:
          requires:
            - verify