version: 2
jobs:
  generate:
    docker: 
      - image: makii42/bindata-builder:latest
    working_directory: /go/src/github.com/makii42/swaggerui
    steps:
      - checkout
      - run: go-bindata -pkg swaggerui -o ./bindata.go ./assets
  check:
    docker:
      - image: makii42/untouched:latest
    working_directory: /go/src/github.com/makii42/swaggerui
    steps: 
      - attach_workspace:
          at: ./dist
      - run: untouched

  test:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: /go/src/github.com/makii42/swaggerui
    steps:
      - run: go build .
      - persist_to_workspace:
          root: ./dist
          paths:
            - "*"


  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./dist
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: mv dist/Dockerfile .
      - run: docker build -t makii42/untouched:latest .
      - run: docker tag makii42/untouched:latest makii42/untouched:$CIRCLE_TAG
      - run: docker push makii42/untouched:latest
      - run: docker push makii42/untouched:$CIRCLE_TAG

workflows:
  version: 2
  build_and_check:
    jobs: 
      - generate
      - check:
          requires: 
            - generate
      - test:
          requires:
            -check